### ISSUE TITLE
View Admin

### ISSUE THREAD

**Issue by sambehrens** [dog-house-development/poodl#40]
Be able to:
- [ ] View admins information, i.e. name, email, phone number
- [ ] Link to edit admin's information
- [ ] _Super-admins only:_ assign a senior center to the current admin if they are a **center** admin
